/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a kpppadaptor -- org.kde.kppp.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KPPPADAPTOR_H_235981150727515
#define KPPPADAPTOR_H_235981150727515

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kppp
 */
class KpppAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kppp")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kppp\" >\n"
"    <method name=\"beginConnect\" />\n"
"    <method name=\"disconnect\" />\n"
"    <method name=\"isConnected\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <signal name=\"aboutToConnect\" />\n"
"    <signal name=\"connected\" />\n"
"    <signal name=\"aboutToDisconnect\" />\n"
"    <signal name=\"disconnected\" />\n"
"  </interface>\n"
        "")
public:
    KpppAdaptor(QObject *parent);
    virtual ~KpppAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void beginConnect();
    void disconnect();
    bool isConnected();
Q_SIGNALS: // SIGNALS
    void aboutToConnect();
    void aboutToDisconnect();
    void connected();
    void disconnected();
};

#endif
