/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a kpppadaptor -- org.kde.kppp.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "kpppadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class KpppAdaptor
 */

KpppAdaptor::KpppAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

KpppAdaptor::~KpppAdaptor()
{
    // destructor
}

void KpppAdaptor::beginConnect()
{
    // handle method call org.kde.kppp.beginConnect
    QMetaObject::invokeMethod(parent(), "beginConnect");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->beginConnect();
}

void KpppAdaptor::disconnect()
{
    // handle method call org.kde.kppp.disconnect
    QMetaObject::invokeMethod(parent(), "disconnect");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->disconnect();
}

bool KpppAdaptor::isConnected()
{
    // handle method call org.kde.kppp.isConnected
    bool out0;
    QMetaObject::invokeMethod(parent(), "isConnected", Q_RETURN_ARG(bool, out0));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->isConnected();
    return out0;
}


#include "kpppadaptor.moc"
